# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('btc', 'BTC'), ('bch', 'BCH'), ('ltc', 'LTC'), ('lsk', 'LSK'), ('eth', 'ETH'), ('dash', 'DASH'), ('neo', 'NEO')], max_length=4)),
                ('rate', models.FloatField()),
                ('amount', models.FloatField(null=True)),
                ('amount_pln', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('btc', 'BTC'), ('bch', 'BCH'), ('ltc', 'LTC'), ('lsk', 'LSK'), ('eth', 'ETH'), ('dash', 'DASH'), ('neo', 'NEO')], max_length=4)),
                ('amount', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletapp.Wallet'),
        ),
    ]
