# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walletapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount_pln',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='currency',
            field=models.CharField(choices=[('BTC', 'BTC'), ('BCH', 'BCH'), ('LTC', 'LTC'), ('LSK', 'LSK'), ('ETH', 'ETH'), ('DASH', 'DASH'), ('NEO', 'NEO')], max_length=4),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('BTC', 'BTC'), ('BCH', 'BCH'), ('LTC', 'LTC'), ('LSK', 'LSK'), ('ETH', 'ETH'), ('DASH', 'DASH'), ('NEO', 'NEO')], max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together=set([('currency', 'user')]),
        ),
    ]
