# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0002_auto_20171122_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('BTC', 'BTC'), ('BCH', 'BCH'), ('LTC', 'LTC'), ('LSK', 'LSK'), ('ETH', 'ETH'), ('DASH', 'DASH'), ('NEO', 'NEO')], max_length=4),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('BTC', 'BTC'), ('BCH', 'BCH'), ('LTC', 'LTC'), ('LSK', 'LSK'), ('ETH', 'ETH'), ('DASH', 'DASH'), ('NEO', 'NEO')], max_length=4),
        ),
    ]
