# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walletapp', '0003_auto_20171123_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_pln', models.FloatField(default=0.0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='currency',
            field=models.CharField(choices=[('BTC', 'BTC'), ('BCH', 'BCH'), ('LTC', 'LTC'), ('LSK', 'LSK'), ('ETH', 'ETH'), ('DASH', 'DASH'), ('NEO', 'NEO')], max_length=4),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('BTC', 'BTC'), ('BCH', 'BCH'), ('LTC', 'LTC'), ('LSK', 'LSK'), ('ETH', 'ETH'), ('DASH', 'DASH'), ('NEO', 'NEO')], max_length=4),
        ),
    ]
